AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for Creating TextractBot Resources

Resources: 
  
  TextractBotLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda-function-textractbot
      CodeUri: ./src/main/python/functions/textractbot_function/
      Handler: main.lambda_handler
      Runtime: python3.8
      Timeout: 5
      MemorySize: 256
      Policies: 
        - arn:aws:iam::aws:policy/AmazonTextractFullAccess
        - arn:aws:iam::123412341234:policy/TextractBot_SecretsManagerFullAccess
      Events: 
        PostApi: 
          Type: Api
          Properties: 
            Path: /textract
            Method: post
            RestApiId: !Ref TextractBotAPI
      Environment:
        Variables:
          SECRETS_MANAGER_SECRET_ARN: arn:aws:secretsmanager:ap-northeast-1:123412341234:secret:secretsmanager-secret-textractbot-XXXXXX

  TextractBotAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: apigw-api-textractbot
      StageName: dev
      EndpointConfiguration: REGIONAL
